name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: bun i --frozen-lockfile
      - name: Build package
        run: bun run build
      - name: Publish package
        run: npx jsr publish --config jsr.json
